- name: Create directories
  file:
    path: "{{ nginx_path }}/{{ item }}"
    state: directory
    owner: "{{ account.user }}"
    group: "{{ account.user }}"
  loop:
    - auth
    - scripts
    - sites-available
    - sites-enabled
    - snippets
    - ssl
    - www
  become: yes

- name: Copy files
  copy:
    src: "{{ item.src }}"
    dest: "{{ nginx_path }}/{{ item.dest }}"
  loop:
    - src: www/dhparam.pem
      dest: ssl/dhparam.pem
  notify:
    - Restart Nginx

- name: Template configuration
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_path }}/{{ item }}"
  loop:
    - docker-compose.yml
    - nginx.conf
  notify:
    - Restart Nginx

- name: Template scripts
  template:
    src: "{{ item }}.j2"
    dest: "{{ nginx_path }}/scripts/{{ item }}"
    mode: "755"
  loop:
    - reload.sh

- name: Create hosts
  block:
    - name: Template host configuration
      template:
        src: host.conf.j2
        dest: "{{ nginx_path }}/sites-available/{{ item.primary }}"
      loop: "{{ hosts }}"
      notify:
        - Restart Nginx

    - name: Activate host
      file:
        src: ../sites-available/{{ item.primary }}
        dest: "{{ nginx_path }}/sites-enabled/{{ item.primary }}"
        state: link
      loop: "{{ hosts }}"
      notify:
        - Restart Nginx

    - name: Check for local files
      local_action: stat path=www/{{ item.primary }}
      loop: "{{ hosts }}"
      register: local_www

    - name: Copy static files if exists
      copy:
        src: www/{{ item.primary }}
        dest: "{{ nginx_path }}/www/"
      when: "'root' not in item and local_www.results[index].stat.exists"
      loop: "{{ hosts }}"
      loop_control:
        index_var: index

    - name: Ensure at least remote directory exists
      file:
        path: "{{ nginx_path }}/www/{{ item.primary }}"
        state: directory
      when: "'root' not in item and not local_www.results[index].stat.exists"
      loop: "{{ hosts }}"
      loop_control:
        index_var: index

- name: Install additional tools
  package:
    name: apache2-utils
    state: present
  become: yes

- name: Start Nginx
  community.general.docker_compose:
    project_src: "{{ nginx_path }}"
    state: present
  become: yes
